### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by SoufianeAjana** [Beirnaert/speaq#3]
Hi,

I am trying to install the package speaq and I have this error:
ERROR: dependencies 'MassSpecWavelet', 'impute' are not available for package 'speaq'

Could you please help me solve this issue,
Soufiane

**Comment by bryanhanson** [comment]
Both of those packages are on Bioconductor.  You can install them via:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("impute")
BiocManager::install("MassSpecWavelet")
```
